pull_request_rules:
  - name: &anchor test-rule
    conditions: []
    actions:
      comment:
        message: "test"
  - name: *anchor
    conditions: []
    actions:
      comment:
        message: "duplicate"
